### ISSUE TITLE
#1 Exception in thread,Traceback (most recent call last)

### ISSUE THREAD

**Issue by akikoyura** [muhammad-ammar/egghead-downloader#1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "downloader.py", line 112, in run
    download_video(directory, url)
  File "downloader.py", line 121, in download_video
    stderr=subprocess.PIPE
  File "C:\Program Files\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python36\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python36\lib\subprocess.py", line 966, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\Python36\lib\subprocess.py", line 461, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable

I've got this problem, can you help me?

**Comment by muhammad-ammar** [comment]
@akikoyura I will look into this as soon as possible. I don't have a windows machine so it may take some time to test.
